spring:
    jmx:
        default-domain: mutiny
    aop.proxy-target-class: true
    datasource:
        url: jdbc:postgresql://localhost:5444/mutiny
        username: mutiny
        password: upstream
        driver-class-name: org.postgresql.Driver
        max-wait: 10000
        test-while-idle: true
        validation-query: SELECT 1
        validation-query-timeout: 1
        initSQL: SELECT 1
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
            hibernate.cache.use_query_cache: true
            net.sf.ehcache.configurationResourceName: /mutiny-ehcache.xml
            hibernate.generate_statistics: true
    rabbitmq:
        addresses: rabbit1
        username: guest
        password: guest
    jackson:
        FAIL_ON_UNKNOWN_PROPERTIES: false
        FAIL_ON_EMPTY_BEANS: false
        serialization:
            WRITE_ENUMS_USING_TO_STRING: true
            FAIL_ON_EMPTY_BEANS: false
            WRITE_DATES_AS_TIMESTAMPS: false
        deserialization:
            READ_ENUMS_USING_TO_STRING: true
            ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
flyway:
    enabled: true
    table: DB_MIGRATION_HISTORY
    sqlMigrationSuffix: .Final.sql
    schemas: mutiny
    outOfOrder: true
security:
  oauth2:
    client:
      clientId: 201488213642907
      clientSecret: c9cb48ec9cac3f5d3389c349b17a2e44
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
logging:
  level:
    org.springframework.security: DEBUG