CREATE TABLE ACCOUNT
(
    ID       BIGSERIAL    NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    EMAIL    VARCHAR(255) NOT NULL,
    TYPE     VARCHAR(50)  NOT NULL,
    CONSTRAINT USER_PK PRIMARY KEY ( ID )
);

CREATE TABLE POST
(
    ID          BIGSERIAL NOT NULL,
    ACCOUNT_ID  BIGINT    NOT NULL,
    CATEGORY_ID BIGINT    NOT NULL,
    CONTENT     VARCHAR(1024),
    CONSTRAINT POST_PK PRIMARY KEY ( ID )
);

CREATE TABLE CATEGORY
(
    ID   BIGSERIAL    NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CONSTRAINT CATEGORY_PK PRIMARY KEY ( ID )
);

CREATE TABLE USER_CATEGORY
(
    ID          BIGSERIAL NOT NULL,
    ACCOUNT_ID  BIGINT    NOT NULL,
    CATEGORY_ID BIGINT    NOT NULL,
    CONSTRAINT USER_CATEGORY_PK PRIMARY KEY (ID)
);

ALTER TABLE POST ADD CONSTRAINT POST_FK01 FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ID);
ALTER TABLE POST ADD CONSTRAINT POST_FK02 FOREIGN KEY ( CATEGORY_ID ) REFERENCES CATEGORY ( ID ) ;

ALTER TABLE USER_CATEGORY ADD CONSTRAINT USER_CATEGORY_FK01 FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ID);
ALTER TABLE USER_CATEGORY ADD CONSTRAINT USER_CATEGORY_FK02 FOREIGN KEY ( CATEGORY_ID ) REFERENCES CATEGORY ( ID ) ;
